#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

# Load bash extensions
for bash_ext in {${EXT_BASH_PROFILE},${EXT_BASH_ALIAS},${EXT_BASH_FUNCS}}; do
	[[ -r "$bash_ext" && -f "$bash_ext" ]] && source "$bash_ext";
done;
unset bash_ext;

# Set gitconfig user extension (precedence to extensions repo vs `gituser`).
# One issue with this is that it causes changes to the tracked `gitconfig`
# file, unsure how to fix right now.
if [[ -r "$EXT_GITCONFIG" && -f "$EXT_GITCONFIG" ]]; then
	git config --global include.path "$EXT_GITCONFIG"
elif [[ -r "$DOTFILES_DIRECTORY"/git/gituser && -f "$DOTFILES_DIRECTORY"/git/gituser ]]; then
	true
	# Leave this out for now since it's already the default in `gitconfig`.
	# git config --global include.path "$DOTFILES_DIRECTORY"/gituser
fi
