#!/usr/bin/env bash

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"

alias ls="ls -G"
alias ll="ls -lG"
alias gls="gls --group-directories-first --color --time-style='+%Y/%m/%d %H:%M:%S'"

alias csh-bash="chsh -s /bin/bash"
alias csh-bash5='chsh -s "${HOMEBREW_PREFIX}"/bin/bash'

# Link the brew openjdk installation so system can find it
alias ln-brew-jdk="ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk"

# Apple extended-attributes
alias ls@="ls -al@"
alias clean-quarantine="xattr -dr com.apple.quarantine ."
alias clean-all-xattr="xattr -c ."
