#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
#
# This file is symlinked to ~/.bash_completion, which is s
# ubsequently sourced by bash-completion@2.

for COMPLETION in "${DOTFILES_DIRECTORY}/shell/completions/"*; do
  [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
done

if [ -d "$EXT_BASH_COMPLETIONS" ]; then
  for COMPLETION in "${EXT_BASH_COMPLETIONS}/"*; do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
  done
fi

unset COMPLETION;
