#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

# Source dotfile_env to set up variables needed for extensions.
source "${HOME}/.dotfiles/dotfiles_env"

HISTTIMEFORMAT="%F %T "
# Better bash completion exp: https://unix.stackexchange.com/a/527944
bind '"\t":menu-complete'
bind "set show-all-if-ambiguous on"
bind "set completion-ignore-case on"
bind "set menu-complete-display-prefix on"
# Use up/down arrow keys to "complete" current command from history
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Load the shell dotfiles, and then some:
for file in ${DOTFILES_DIRECTORY}/shell/{bash_prompt,functions,bash_aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# brew
[[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

# Android studio
NDK_VERSION=21.4.7075529
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_NDK=$ANDROID_HOME/ndk/$NDK_VERSION
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
# Add VSCode to path
export PATH="${PATH}:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# Add dotfiles bin to path
export PATH="${PATH}:${DOTFILES_DIRECTORY}/bin"

# Jdk path - currently v.11
export JAVA_HOME=$(/usr/libexec/java_home -v 11)

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Add tab completion for many Bash commands: https://docs.brew.sh/Shell-Completion#configuring-completions-in-bash
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
fi

# Source chruby so it becomes source of truth for ruby version to use
CHRUBY_PATH="$(brew --prefix)/opt/chruby/share/chruby"
source "$CHRUBY_PATH"/chruby.sh
source "$CHRUBY_PATH"/auto.sh

# Init bash dotfile extensions
source "$DOTFILES_DIRECTORY"/shell/bash_ext_init
