#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

export DOTFILES_DIRECTORY="${HOME}/.dotfiles"
export DOTFILES_EXT_DIRECTORY="${HOME}/.dotfiles_exts"

export EXT_GITCONFIG="${DOTFILES_EXT_DIRECTORY}/gitconfig"
export EXT_BASH_PROFILE="${DOTFILES_EXT_DIRECTORY}/bash_profile"
export EXT_BASH_ALIAS="${DOTFILES_EXT_DIRECTORY}/bash_aliases"
export EXT_BASH_FUNCS="${DOTFILES_EXT_DIRECTORY}/bash_functions"
export EXT_VSCODE_SETTINGS="${DOTFILES_EXT_DIRECTORY}/vscode_settings.json"
export EXT_BASH_COMPLETIONS="${DOTFILES_EXT_DIRECTORY}/completions"
