#!/usr/bin/env bash

export DOTFILES_DIRECTORY="${HOME}/.dotfiles"
export DOTFILES_EXT_DIRECTORY="${HOME}/.dotfiles_exts"

# Source config, as env files depend on it.
source "$DOTFILES_DIRECTORY/config" 2>/dev/null

# check if DOTFILES_EXT_PATH is set (or if it's a non-zero length string)
if [ -n "$DOTFILES_EXT_PATH" ]; then
  [ -f "${DOTFILES_EXT_PATH}/gitconfig" ] && export EXT_GITCONFIG="${DOTFILES_EXT_PATH}/gitconfig"
  [ -f "${DOTFILES_EXT_PATH}/bash_profile" ] && export EXT_BASH_PROFILE="${DOTFILES_EXT_PATH}/bash_profile"
  [ -f "${DOTFILES_EXT_PATH}/bash_aliases" ] && export EXT_BASH_ALIAS="${DOTFILES_EXT_PATH}/bash_aliases"
  [ -f "${DOTFILES_EXT_PATH}/bash_functions" ] && export EXT_BASH_FUNCS="${DOTFILES_EXT_PATH}/bash_functions"
  [ -f "${DOTFILES_EXT_PATH}/vscode_settings_json" ] && export EXT_VSCODE_SETTINGS="${DOTFILES_EXT_PATH}/vscode_settings.json"
fi
