#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
#
# This file is symlinked to ~/.bash_completion, which is s
# ubsequently sourced by bash-completion@2.


for COMPLETION_DIRECTORY in {"${DOTFILES_DIRECTORY}/shell/common/completions/","$EXT_COMPLETIONS"}; do
  if [ -d "$COMPLETION_DIRECTORY" ]; then
    for COMPLETION in "${COMPLETION_DIRECTORY}/"*; do
      [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
    done
  fi
done

unset COMPLETION COMPLETION_DIRECTORY;
