#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
#
# Entry point to initialize extensions for bash and git.

# Load bash extensions
for bash_ext in {$EXT_BASH_PROFILE,$EXT_FUNCS,$EXT_ALIASES}; do
  [[ -r "$bash_ext" ]] && source "$bash_ext";
done;
unset bash_ext;

# Set gitconfig user extension (precedence to extensions repo vs `gituser`).
if [[ -r "$EXT_GITCONFIG" ]]; then
  git config --global include.path "$EXT_GITCONFIG"
elif [[ -r "$DOTFILES_DIRECTORY"/git/gituser ]]; then
  git config --global include.path "$DOTFILES_DIRECTORY"/git/gituser
fi
