#!/bin/zsh

source "${HOME}/.dotfiles/dotfiles_env"
source "${DOTFILES_DIRECTORY}/shell/common/shprofile"
source "${DOTFILES_DIRECTORY}/shell/zsh/zprompt"

HOMEBREW_PREFIX="$(brew --prefix)"

# history file
export HISTFILE=~/.zsh_history
# history format
alias history="history -t '%F %T'" 
# don't show duplicate history entires
setopt hist_find_no_dups
# remove unnecessary blanks from history
setopt hist_reduce_blanks
# share history between instances
setopt share_history
setopt extended_history

# autocorrect command spelling
setopt correct
# setopt correctall

# expand parameters, commands and arithmetic in prompts
setopt prompt_subst

# impacts tab
setopt bash_auto_list
setopt complete_aliases
# unsetopt ALWAYS_LAST_PROMP

# case insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

# style ZSH output
zstyle ':completion:*:descriptions' format '%U%B%F{red}%d%f%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# dotfiles repo completions, and ext completions
# FPATH="${DOTFILES_DIRECTORY}/shell/zsh/completions:${EXT_ZSH_COMPLETIONS}:${FPATH}"
if type brew &>/dev/null; then
  FPATH="${HOMEBREW_PREFIX}/share/zsh/site-functions:${FPATH}"
fi

# completion initialization
autoload -Uz compinit && compinit
# enable bash completion compatability, and source bash completion files
autoload -Uz bashcompinit && bashcompinit
source "$DOTFILES_DIRECTORY/shell/bash/bash_completion"

# colorful prompt with Git and Subversion branch
autoload -U colors && colors

# search through history with up and down arror
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# zsh-autosuggestions / zsh-syntax-highlighting
ZSH_AUTOSUGGEST_HISTORY_IGNORE="(git commit -m *|git ci -m *)"
if [[ -r "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
    source "${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi
if [[ -r "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
    source "${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# enable mcfly (if installed)
type mcfly &>/dev/null && eval "$(mcfly init zsh)"

# Init zsh dotfile extensions
[[ -r "$EXT_ZPROFILE" ]] && source "$EXT_ZPROFILE";
source "$DOTFILES_DIRECTORY/shell/common/sh_ext_init"
