#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
#
# Entry point to initialize extensions for shell aliases/functions and git.

# Load shell extensions
for sh_ext in {$EXT_FUNCS,$EXT_ALIASES}; do
  [[ -r "$sh_ext" ]] && source "$sh_ext";
done;
unset sh_ext;

# Set gitconfig user extension (precedence to extensions repo vs `gituser`).
if [[ -r "$EXT_GITCONFIG" ]]; then
  git config --global include.path "$EXT_GITCONFIG"
elif [[ -r "$DOTFILES_DIRECTORY"/git/gituser ]]; then
  git config --global include.path "$DOTFILES_DIRECTORY"/git/gituser
fi
