on: [push]
name: Dotfiles tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: install-all
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dotfiles installation
        shell: bash
        run: |
          rm -f /usr/local/bin/2to3 || :
          rm -f /usr/local/bin/2to3-3.11 || :
          rm -f /usr/local/bin/idle3 || :
          rm -f /usr/local/bin/idle3.11 || :
          rm -f /usr/local/bin/pydoc3 || :
          rm -f /usr/local/bin/pydoc3.11 || :
          rm -f /usr/local/bin/python3 || :
          rm -f /usr/local/bin/python3.11 || :
          rm -f /usr/local/bin/python3-config || :
          rm -f /usr/local/bin/python3.11-config || :
          ./bin/dotfiles install-all --no-sync
        env:
          TERM: dumb
